### PR TITLE
Set cookie attributes

### PR DESCRIPTION
**Pull request by paluh**
If you decide to merge #55 then this pull request should show only cookie related changes as is rebased (and tested) on the top of `writeString` related commits...

### CODE REVIEW

**Comment by paluh** [comment]
This pull request has also been adapted to newest master version.

**Comment by paluh** [comment]
@owickstrom I'm not sure how it is possible, but travis fails on this pull request because of some tests which are no longer on this branch (just check failing tests names from travis report). When I'm running this on my local machine everything is fine.
In other words this pull request is ready for merge if you find it useful.

**Comment by owickstrom** [comment]
Strange! I'll look at this when I have some time soon. Sorry for the wait.

**Comment by owickstrom** [comment]
Might have been the build cache. I've cleared it and restarted the PR build in Travis.

**Comment by paluh** [comment]
I'm closing this as I'm going to provide separate clear PR with only related changes.

**Pull request closed without merging**
