### PR TITLE
Upgrade to purescript-aff v4

### PR DESCRIPTION
**Pull request by owickstrom**
Fixes https://github.com/owickstrom/hyper/issues/49. @coot, any feedback? I haven't had time to look much at the new API for AVar, so a review would be nice.

### CODE REVIEW

**Comment by coot** [comment]
I'll have a look soon, just give me some time (~a week).

**Comment by i-am-the-slime** [comment]
Let's go!

**Comment by owickstrom** [comment]
Would like an ack from @coot as well :)

**Comment by coot** [comment]
Looks good to me, sorry for a late review.

**Pull request merged**
