### PR TITLE
Write strings as chunks into the Node response stream

### PR DESCRIPTION
**Pull request by owickstrom**
This seems to help with the trouble in #37, based on my reproduction of the problem, but I'm pretty sure it is just a band-aid. AFAIK, the drain event isn't exposed in the Buffer library, and I think we need that to fix this for real.

Anyway, @justinwoo, would you like to try this branch on your project?

### CODE REVIEW

**Comment by justinwoo** [comment]
Cool, it works, thanks!

I also tried to break it by forcing it to take more chunks per tick (by manually editing the build output), but couldn't really figure out a way to make it actually fail. Maybe eventually the optimistic fire-and-forget might not work, but I don't know when that would happen 😄

**Comment by owickstrom** [comment]
OK, nice! Yeah, I think it would need to take the `drain` event into consideration, but it would have to be added to purescript-node-buffer. I'll try doing that when I get some time.

**Comment by owickstrom** [comment]
I'll keep this PR open for now, as this currently feels a bit half-baked.

**Comment by paluh** [comment]
I'm not sure why, but it seems that `writeString` callback is never called when response is an empty `String` (so `succeed` is never called too).
What is even more strange I was not able to get the same result directly when testing `node-streams`. I'm going to investigate this issue further when I have spare time.

Please test this simple scenario if you can and give me some feedback if you also observing this hanging response on this branch in case of empty response body.

**Comment by paluh** [comment]
@owickstrom  I've addapted your aff upgrade to work with this branch, but I'm not sure what to do about it:

https://github.com/paluh/hyper/commit/3a408969dea3df43f81210b5c7f304052b279b0d

**Comment by paluh** [comment]
In general we are working on the branch of this branch, because 16Kb response limit is unacceptable in our times ;-)

**Comment by owickstrom** [comment]
I just merged the Aff 4 upgrade to master, could you rebase your branch on that first? 👍

**Comment by paluh** [comment]
I'm closing this - for details please check this PR thread: https://github.com/owickstrom/hyper/pull/55

**Pull request closed without merging**
