### PR TITLE
FileServer: add simple content type detection

### PR DESCRIPTION
**Pull request by paluh**
Sets content type based on file extension predefined in static map in `FileServer.purs`.

### CODE REVIEW

**Comment by paluh** [comment]
This PR slightly extends behavior of `FileServer`. It introduces mapping between file extension and `ContentType` header value. Mapping was taken from:

https://www.askapache.com/htaccess/

and

https://htaccess.wordpress.com/2008/07/16/sending-correct-content-type-headers-with-htaccess/

Merge?

**Comment by paluh** [comment]
I can also use your suggestion from https://github.com/owickstrom/hyper/pull/57 and add this content type mapping as a parameter to server options record (together with `userProvidedHeaders` from this other PR). What do you think?

**Comment by owickstrom** [comment]
Looks good @paluh ! I say merge this, and then do the header user function separately. :+1:

**Comment by paluh** [comment]
Thanks!

**Pull request merged**
