### PR TITLE
Add all HTTP 1.1 methods for type level router

### PR DESCRIPTION
**Pull request by garyb**
I'm not sure if you actually want contributions to this project, so if not please disregard! :smile:

I split the methods out into their own module, as I figured having a type named `Options` in there is a bit opaque, so having it in a module explicitly for methods at least should help communicate it's not a type representing some options for the router or something. I can merge them back in if you disagree though.

edit: I wasn't really sure what the expected behaviour was for the `DataRouter`, so that `pure Nothing` is probably wrong.

### CODE REVIEW

**Comment by owickstrom** [comment]
I do, it's very nice to have you here! :)

Regarding HTTP methods, I was thinking about using https://github.com/purescript-contrib/purescript-http-methods/blob/master/src/Data/HTTP/Method.purs, just haven't gotten around to changing it. Do you think that would work?

The `Options` thing looks good. I agree that it is much more clear this way.

For the `DataRouter` and `pure Nothing`, that means it will, as it's a `TryMiddleware` with an `Alt` instance, fall through to the next middleware. That fallback is probably a 404 response. So `pure Nothing` means "I cannot route this". If you look at https://github.com/garyb/hyper/blob/a3f3902d5376a2dfca38cd865a2e01973138ddd3/test/Hyper/Routing/DataRouterSpec.purs#L118 you see the quite hacky way of passing a handler matcher into the router. I couldn't get it to work with just passing the `handler` as is, the type checker and exhaustiveness checker did not like this kind of GADT-style trickery. So, to support all methods the user of `router` would have to pass the handler for all methods used, e.g. `{ get: handler, post: handler, put: handler, patch: handler ... }`. Not that elegant, IMO. 😜 

Anyway, I haven't put much effort into `ResourceRouter` and `DataRouter` lately as I think the type-level router will be the survivor of this experiment (I wanted to try a number of different router designs and see which comes out best). 

* The record-based `ResourceRouter` is OK, but the type signatures are horrible, and mutual references between resources are very complex. Also control over URLs is a bit clunky.
* `DataRouter` is kind of nice in that you get pattern matching over your routes, and it's a beginner-friendly design IMO. It's really a port of a design I made in Haskell using GADTs, and without GADTs it's a bit crippled. Leibniz equality only get's you so far, you need the exhaustiveness checker to play along here. The routing instances, parsing path pieces, and control over URLs are still concerns which you have to create instances (manually) for. Maybe it could be derived generically, but I do not know where to fit in URL control.
* `TypeLevelRouter` is mostly a clone of servant-server right now. I really like that design and flexibility, and I have some plans on what we can do with it next. 😄 It solves many of the problems in the other routers, mostly around extensibility, but also control of URLs. I'm currently working on providing Servant-style handlers that are just functions of your domain types, and making Hyper middleware at endpoints possible through a `Raw` handler construct.

Anyway... maybe it's not time to scrap the other routers just yet. Thoughts? Sorry to drown you in information! 😄

**Comment by owickstrom** [comment]
Just realized we only support `GET` and `POST` in the `DataRouter` anyway, so the `pure Nothing` is good. 👍

**Comment by owickstrom** [comment]
Some tests are not passing, or not compiling, it seems.

**Comment by owickstrom** [comment]
OK, this is merged now. Thanks for the PR! 👍  GitHub does not seem to recognize the PR merge as I had to rebase and do some fixes, and probably messed up the merge commit somehow.

**Comment by garyb** [comment]
> Regarding HTTP methods, I was thinking about using https://github.com/purescript-contrib/purescript-http-methods/blob/master/src/Data/HTTP/Method.purs, just haven't gotten around to changing it. Do you think that would work?

Yeah, definitely! I wasn't sure if you were avoiding it intentionally for some reason, otherwise I might have done that instead. 

There's a similar thing for HTTP headers, but is woefully under-implemented - I wanted to cover a bunch of the common headers described in RFCs, but also have them use proper types rather than just `String` values, so for now it's probably not worth using.

---

I must admit I didn't really try out the other routers at all, as I was eager to try out the type-based one :wink:. So I can't really comment on whether they should be dropped yet. The type-level one depends on the `ResourceRouter` currently anyway, doesn't it? I didn't realise that at first, but when none of my new methods worked I realised changes were needed elsewhere too.

**Comment by owickstrom** [comment]
> Yeah, definitely! I wasn't sure if you were avoiding it intentionally for some reason, otherwise I might have done that instead.

OK, then we should use that. 👍 

> The type-level one depends on the ResourceRouter currently anyway, doesn't it? I didn't realise that at first, but when none of my new methods worked I realised changes were needed elsewhere too.

I don't think it does, but if it does then that's a mistake on my part. Do you know where that might be?

**Comment by garyb** [comment]
I'm not sure, maybe I did something else wrong :smile: - the initial commit in my PR didn't work on its own though, the followup commit seemed to do it. 

Now I'm looking again perhaps it was just the additions to `Method` that did it though.

**Comment by owickstrom** [comment]
Might have been that, yes. `TypeLevelRouter` depends on `Method` for `HTTPError`.

By the way, I just pushed some new stuff today. Monadic handlers, ability to throw HTTP errors in handlers (like the "post not found" scenario), and `Raw` middleware handlers:
https://github.com/owickstrom/hyper/blob/master/examples/type-level-routing/Main.purs#L81-L97

**Pull request closed without merging**
