### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by nsaunders**

### CODE REVIEW

**Comment by nsaunders** [comment]
Updates: I've upgraded the Argonaut dependencies to align better with [purescript-trout#8](https://github.com/owickstrom/purescript-trout/pull/8) since I plan on updating [purescript-hypertrout](https://github.com/owickstrom/purescript-hypertrout) after these PRs are merged.

I also realized that Travis CI was failing due to examples and docs referring to the old ```Control.IxMonad``` module instead of ```Control.Monad.Indexed```, so I have resolved that as well.

**Comment by nsaunders** [comment]
Hey there @owickstrom, I was wondering if anything is looking questionable to you so far. I would like to address any problems ASAP so we can hopefully look at releasing a new version. :-)

EDIT: Just remembered--it would probably be good for me to tackle #65 once this is merged, though.

**Comment by owickstrom** [comment]
All looks good. Thanks @nicholassaunders!

**Comment by owickstrom** [comment]
And yeah, if you wanted to #65 that would be nice, or if you mark it as "Good first issue" someone could pick it up.

**Pull request merged**
