### PR TITLE
updates for 0.11

### PR DESCRIPTION
**Pull request by justinwoo**
I also tried to make some of the formatting uniform, but if any of the changes look ugly, I can fix them. Going to try updating my app off this branch and see what happens.

edit:

it worked! https://github.com/justinwoo/vidtracker/commit/75cc1d736d15ab03f787cadb2eaa3b5a4b54c552

### CODE REVIEW

**Comment by justinwoo** [comment]
I updated the branch with the new releases, and then I'm just using a commit hash for the dev spec-discovery dependency. I can update it if you publish spec-discovery, but shouldn't be necessary I guess

**Comment by justinwoo** [comment]
updated with latest spec-discovery! edit: i'll have to edit the examples sometime

**Comment by justinwoo** [comment]
fixed the topic-guides and examples, but the type-level-routing example i guess will have to wait for some upstream things, but requires some hackery for what release is even available and whatnot i guess?

**Comment by owickstrom** [comment]
Ah yes, that's a mess. Because of bower forcing 1:1 package and git repos I cannot have all the Hyper packages in one repository. But I version the documentation in this repo, and thus the examples depend on other hyper packages, basically creating circular dependencies. I should perhaps move those guides and examples and just link to them instead.

**Comment by owickstrom** [comment]
OK, I disabled the build of the type level examples and docs. They should be moved out to the corresponding repository, I'll do that later. Thanks so much for your work! I'll release this ASAP.

**Comment by owickstrom** [comment]
OK, `v0.7.0` released now.

**Pull request merged**
