### PR TITLE
Actually use `options.hostname` in `runServer`

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by paluh** [comment]
Probably hostname should be used also in here, because this message can be missleading:

https://github.com/owickstrom/hyper/blob/master/src/Hyper/Node/Server.purs#L237

I can provide this trivial pull request. Should I add `newtype Hostname` type and add another argument to  `onListening`?

**Comment by owickstrom** [comment]
Thanks for the PR!

Yeah, doing the same thing as with `Port` sounds good. You can add it in this PR if you want, it's so simple anyway.

**Comment by paluh** [comment]
I've extracted separate module `Hyper.Node.Server.Options` for types and defaults. Of course If you don't like this arrangement I can revert it and bring back previous modules structure. Just let me know!

**Comment by owickstrom** [comment]
Looks good, the reexport keeps it compatible as well. Thank you!

**Pull request merged**
