### PR TITLE
Use qualified do notation where relevant

### PR DESCRIPTION
**Pull request by JordanMartinez**
Builds off of #86 and uses new `purescript-indexed-monad` release, which includes a file for qualified do, to remove the `writeStatus :*> closeHeaders` style of code for normal do notation via qualified do notation.

### CODE REVIEW

**Comment by nsaunders** [comment]
Thanks for the PR. FYI: [`Hyper.Middleware.QualifiedDo`](https://github.com/owickstrom/hyper/blob/master/src/Hyper/Middleware/QualifiedDo.purs)

**Comment by JordanMartinez** [comment]
I'm aware of that file, but I thought it odd that such a file existed here rather than in the `purescript-indexed-monads` library, where it seemed more appropriate.

**Comment by JordanMartinez** [comment]
With #86 closed, is this change desired if I rebased it?

**Comment by nsaunders** [comment]
Indeed, I think it's a reasonable change. 👍

**Comment by JordanMartinez** [comment]
Done.

**Comment by nsaunders** [comment]
Thanks @JordanMartinez !

**Pull request merged**
